name: Maven CI/CD

on:
  push:
    branches: [ Development ]

jobs:
  CI_Test_And_Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Configurar JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Ejecutar pruebas con maven
        run: mvn -B test