name: Maven CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Hacemos Checkuot del repo de Git
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Test project with Maven E9
        run: mvn -B test

      - name: Build project with Maven
        run: mvn -B package

      - name: Get Version from POM.xml
        uses: entimaniac/read-pom-version-action@1.0.0
        id: getVersion
      
      - name: Copy generated .war to staging
        run: mkdir staging && cp target/*.war staging

      - name: Upload generated .war to Artifact 
        uses: actions/upload-artifact@v3
        with:
          name: mvn-hello-world-${{ steps.getVersion.outputs.version }}.zip
          path: staging  